# Generated by Django 4.0.2 on 2022-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myModel', '0002_alter_stereoimages_stereoimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='stereoimages',
            name='email',
            field=models.CharField(default='', max_length=500),
        ),
    ]
